### ISSUE TITLE
QueryParameterException: could not locate named parameter [author]

### ISSUE THREAD

**Issue by tproenca** [uci-sdcl/lighthouse#62]
<i>Lee Martie(leemartie) reported on 2011-10-13</i>

On line 68 in edu.uci.lighthouse.core.controller.PullModel, the method, executeNamedQuery, is being called that instantiates the named query with some arguments.

I believe the problem with the code here, is that it is trying to pass an argument for the "author" parameter, but
there is no author parameter in the named query.

Commenting out the code responsible for producing the exception (line 67 in edu.uci.lighthouse.core.controller.PullModel) fixes the problem and the Lighthouse demo runs. Before resolving this as the solution though, testing of the consequences of this solution needs to be done.

> The original Bugzilla issue report should still be here: http://calico.ics.uci.edu/bugs/show_bug.cgi?id=67

**Comment by tproenca** [comment]
<i>Lee Martie(leemartie) reported on 2011-10-13</i>

## Exception:

<pre>
2011-08-13 02:20:55,364 ERROR [edu.uci.lighthouse.core.data.DatabaseActionsThread] (DatabaseActionsThread.java:101) - java.lang.IllegalArgumentException: org.hibernate.QueryParameterException: could not locate named parameter [author]

java.lang.IllegalArgumentException: org.hibernate.QueryParameterException: could not locate named parameter [author]
    at org.hibernate.ejb.QueryImpl.setParameter(QueryImpl.java:206)
    at edu.uci.lighthouse.model.jpa.AbstractDAO.executeNamedQuery(AbstractDAO.java:51)
    at edu.uci.lighthouse.core.controller.PullModel.getNewEventsFromDB(PullModel.java:68)
    at edu.uci.lighthouse.core.dbactions.pull.FetchNewEventsAction.run(FetchNewEventsAction.java:25)
    at edu.uci.lighthouse.core.data.DatabaseActionsThread.processBuffer(DatabaseActionsThread.java:88)
    at edu.uci.lighthouse.core.data.DatabaseActionsThread.run(DatabaseActionsThread.java:53)
Caused by: org.hibernate.QueryParameterException: could not locate named parameter [author]
    at org.hibernate.engine.query.ParameterMetadata.getNamedParameterDescriptor(ParameterMetadata.java:99)
    at org.hibernate.engine.query.ParameterMetadata.getNamedParameterExpectedType(ParameterMetadata.java:105)
    at org.hibernate.impl.AbstractQueryImpl.determineType(AbstractQueryImpl.java:437)
    at org.hibernate.impl.AbstractQueryImpl.setParameter(AbstractQueryImpl.java:407)
    at org.hibernate.ejb.QueryImpl.setParameter(QueryImpl.java:201)
    ... 5 more
</pre>

**Comment by tproenca** [comment]
<i>Lee Martie(leemartie) reported on 2011-10-14</i>

A named query (LighthouseEvent.findByTimestamp) was rewritten in the LighthouseEvent class and it dropped the parameter "author" (the history says it was for a student named Kyle).
This created an exception because the method, executeNamedQuery, in class PullModel (line 68) was trying to pass an argument to the parameter authur, but there was not one.
This was resolved by changing the query in the named query (LighthouseEvent.findByTimestamp) to its previously defined query. The demo now works.
